// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Configuration of virtual machine scale set which is part of the scale
    /// group.
    /// </summary>
    public partial class ScaleSetConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the ScaleSetConfiguration class.
        /// </summary>
        public ScaleSetConfiguration()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ScaleSetConfiguration class.
        /// </summary>
        /// <param name="name">The name used as an identifier of this VM scale
        /// set configuration.</param>
        /// <param name="autoscaleSettingsResourceId">The resource id of the
        /// autoscale settings which controls virtual machine scale set
        /// scaling.</param>
        /// <param name="profileName">The name of the profile of autoscale
        /// settings which is used to control VMSS scaling.</param>
        /// <param name="requestsPerInstance">The number of requests per VMSS
        /// instance</param>
        /// <param name="minInstanceCount">The minimal number of instances
        /// defined in the profile.</param>
        /// <param name="defaultInstanceCount">The default number of instances
        /// defined in the profile.</param>
        public ScaleSetConfiguration(string name, string autoscaleSettingsResourceId, string profileName, int? requestsPerInstance = default(int?), int? minInstanceCount = default(int?), int? defaultInstanceCount = default(int?))
        {
            Name = name;
            AutoscaleSettingsResourceId = autoscaleSettingsResourceId;
            ProfileName = profileName;
            RequestsPerInstance = requestsPerInstance;
            MinInstanceCount = minInstanceCount;
            DefaultInstanceCount = defaultInstanceCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the name used as an identifier of this VM scale set
        /// configuration.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the resource id of the autoscale settings which
        /// controls virtual machine scale set scaling.
        /// </summary>
        [JsonProperty(PropertyName = "autoscaleSettingsResourceId")]
        public string AutoscaleSettingsResourceId { get; set; }

        /// <summary>
        /// Gets or sets the name of the profile of autoscale settings which is
        /// used to control VMSS scaling.
        /// </summary>
        [JsonProperty(PropertyName = "profileName")]
        public string ProfileName { get; set; }

        /// <summary>
        /// Gets or sets the number of requests per VMSS instance
        /// </summary>
        [JsonProperty(PropertyName = "requestsPerInstance")]
        public int? RequestsPerInstance { get; set; }

        /// <summary>
        /// Gets or sets the minimal number of instances defined in the
        /// profile.
        /// </summary>
        [JsonProperty(PropertyName = "minInstanceCount")]
        public int? MinInstanceCount { get; set; }

        /// <summary>
        /// Gets or sets the default number of instances defined in the
        /// profile.
        /// </summary>
        [JsonProperty(PropertyName = "defaultInstanceCount")]
        public int? DefaultInstanceCount { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (AutoscaleSettingsResourceId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AutoscaleSettingsResourceId");
            }
            if (ProfileName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ProfileName");
            }
            if (RequestsPerInstance > 1000000000)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "RequestsPerInstance", 1000000000);
            }
            if (RequestsPerInstance < 0)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "RequestsPerInstance", 0);
            }
            if (MinInstanceCount > 1000)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "MinInstanceCount", 1000);
            }
            if (MinInstanceCount < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "MinInstanceCount", 1);
            }
            if (DefaultInstanceCount > 1000)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "DefaultInstanceCount", 1000);
            }
            if (DefaultInstanceCount < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "DefaultInstanceCount", 1);
            }
        }
    }
}
