// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ScheduledScaleEvent
    {
        /// <summary>
        /// Initializes a new instance of the ScheduledScaleEvent class.
        /// </summary>
        public ScheduledScaleEvent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ScheduledScaleEvent class.
        /// </summary>
        public ScheduledScaleEvent(System.Guid? id = default(System.Guid?), string name = default(string), System.DateTimeOffset? requiredScaleAt = default(System.DateTimeOffset?), System.DateTimeOffset? estimatedScaleUpAt = default(System.DateTimeOffset?), System.DateTimeOffset? startScaleDownAt = default(System.DateTimeOffset?), IList<RegionScaleValue> regionConfig = default(IList<RegionScaleValue>))
        {
            Id = id;
            Name = name;
            RequiredScaleAt = requiredScaleAt;
            EstimatedScaleUpAt = estimatedScaleUpAt;
            StartScaleDownAt = startScaleDownAt;
            RegionConfig = regionConfig;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requiredScaleAt")]
        public System.DateTimeOffset? RequiredScaleAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "estimatedScaleUpAt")]
        public System.DateTimeOffset? EstimatedScaleUpAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startScaleDownAt")]
        public System.DateTimeOffset? StartScaleDownAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "regionConfig")]
        public IList<RegionScaleValue> RegionConfig { get; set; }

    }
}
