// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CosmosConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the CosmosConfiguration class.
        /// </summary>
        public CosmosConfiguration()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CosmosConfiguration class.
        /// </summary>
        public CosmosConfiguration(string name, string accountName, string databaseName, string containerName = default(string), double? requestUnitsPerRequest = default(double?), int? minimumRU = default(int?), int? maximumRU = default(int?))
        {
            Name = name;
            AccountName = accountName;
            DatabaseName = databaseName;
            ContainerName = containerName;
            RequestUnitsPerRequest = requestUnitsPerRequest;
            MinimumRU = minimumRU;
            MaximumRU = maximumRU;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountName")]
        public string AccountName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "databaseName")]
        public string DatabaseName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "containerName")]
        public string ContainerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestUnitsPerRequest")]
        public double? RequestUnitsPerRequest { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minimumRU")]
        public int? MinimumRU { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maximumRU")]
        public int? MaximumRU { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (AccountName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AccountName");
            }
            if (DatabaseName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DatabaseName");
            }
        }
    }
}
