// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class ScaleGroupRegion
    {
        /// <summary>
        /// Initializes a new instance of the ScaleGroupRegion class.
        /// </summary>
        public ScaleGroupRegion()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ScaleGroupRegion class.
        /// </summary>
        public ScaleGroupRegion(string regionName, IList<ScaleSetConfiguration> scaleSets, IList<CosmosConfiguration> cosmos = default(IList<CosmosConfiguration>), TimeSpan scaleSetPrescaleLeadTime = default(TimeSpan), TimeSpan cosmosDbPrescaleLeadTime = default(TimeSpan), int? maxScale = default(int?), TimeSpan maxLeadTime = default(TimeSpan))
        {
            RegionName = regionName;
            ScaleSets = scaleSets;
            Cosmos = cosmos;
            ScaleSetPrescaleLeadTime = scaleSetPrescaleLeadTime;
            CosmosDbPrescaleLeadTime = cosmosDbPrescaleLeadTime;
            MaxScale = maxScale;
            MaxLeadTime = maxLeadTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "regionName")]
        public string RegionName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scaleSets")]
        public IList<ScaleSetConfiguration> ScaleSets { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cosmos")]
        public IList<CosmosConfiguration> Cosmos { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scaleSetPrescaleLeadTime")]
        public TimeSpan ScaleSetPrescaleLeadTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cosmosDbPrescaleLeadTime")]
        public TimeSpan CosmosDbPrescaleLeadTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxScale")]
        public int? MaxScale { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxLeadTime")]
        public TimeSpan MaxLeadTime { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RegionName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RegionName");
            }
            if (ScaleSets == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ScaleSets");
            }
            if (RegionName != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(RegionName, "^[\\d\\w\\s-]*$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "RegionName", "^[\\d\\w\\s-]*$");
                }
            }
            if (ScaleSets != null)
            {
                foreach (var element in ScaleSets)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (Cosmos != null)
            {
                foreach (var element1 in Cosmos)
                {
                    if (element1 != null)
                    {
                        element1.Validate();
                    }
                }
            }
        }
    }
}
